### ISSUE TITLE
Demo & Screenshots

### ISSUE THREAD

**Issue by kentcdodds** [phamductri/turn-calendar#1]
Would be very helpful in getting a feel for what this library does :-)

**Comment by kentcdodds** [comment]
I recommend jsbin personally :+1: 

Definitely considering this library. I want to get rid of the jQuery UI calendar picker. Was planning on writing my own, because I haven't found one that supported multiple months. It looks like this one supports that :-)

**Comment by kentcdodds** [comment]
Just noticed [this](http://phamductri.github.io/turn-calendar/demo/). Would be cool to get a link to that in the README.md :-)

**Comment by phamductri** [comment]
Link has been merged. Thanks for the feedback :D
