### ISSUE TITLE
Ho do I add year beside month in calendar

### ISSUE THREAD

**Issue by rakeshch** [phamductri/turn-calendar#13]
Hi,

The control looks great but as you keep on moving to the previous months there is no way of notifying a user which year he is in . I am trying to add year beside month in calendar popup but not successful so far. Can you please help me out?

Thanks,

**Comment by phamductri** [comment]
hi, if you notice the previousMonth() and nextMonth() functions control the flow of the calendar. You can set a scope variable in these functions to indicate the current year. I hope this help.

**Comment by rakeshch** [comment]
Awesome, that works. Thanks.

One more quick question: How do I change the format of the startdate/enddate string to 01 July 2015?

**Comment by phamductri** [comment]
I plan to add the ability to change the startdate/enddate string per user specified format. I'm not sure how to do the proper formatting, either by relying on some third party JS like moment.js, or write my own formatting function

**Comment by bcherny** [comment]
@phamductri 

``` js
let date = new Date()
let format = 'dd MMMM yyyy'
let formattedDate = $filter('date')(date, format)
```

**Comment by rakeshch** [comment]
How did I miss that date filter.Thank you somuch bcherny and phamductri.

I applied date filter inside the template(wherever required) and everything works like charm.
(startDateString.date | date:'dd MMMM yyyy')

Regards,
Rakesh
