### ISSUE TITLE
How to get the selected start date and end date?

### ISSUE THREAD

**Issue by Divyaadz** [phamductri/turn-calendar#7]
Using below code in angular js. I like to get the selected start date and end date, Please provide the syntax. not able to access 'startDateString'

Please help. Thanks

<turn-calendar calendar-options="calendarOptions"></turn-calendar>

 $scope.calendarOptions = {
            startDayOfWeek: 1,
            backwardMonths: 2,
            minSelectDate: '9/13/2013',
            weeklySelectRange: 60,
            monthlySelectRange: 90,
            minBackwardMonth: '08/2013',
            priorRangePresets: [{value: 7}, {value: 30, isDefault: true}, {value : 45}]
        };

**Comment by phamductri** [comment]
to get the selected start date and end date you need to pass in two variables into startDate and endDate directive
<turn-calendar start-date="firstDate" end-date="secondDate">

To retrieve you wrap it in a $timeout service: 
$timeout(function () {
console.log($scope.firstDate);
console.log($scope.secondDate);
});

Try this, you will see this everytime you selected something, firstDate and secondDate are updated to the values you select. I will update the docs to make this more clear
